### 
GET http://localhost:8080/api/categories

###
GET http://localhost:8080/api/products

###
GET http://localhost:8080/api/products/iphone-14-proxxc

###
POST http://localhost:8080/api/categories
content-Type: application/json

{
    "category_name":"Mobile",
    "category_ascii":"mobile"
}

###
POST http://localhost:8080/api/brands
content-Type: application/json

{
    "brand_name":"Samsung",
    "brand_ascii":"samsung",
    "category_id":"1"
}





###
POST http://localhost:8080/api/products
content-Type: application/json

{
    "product_name":"iPhone 14 Pro",
    "product_ascii":"iphone-14-pro",
    "category_ascii": "mobile",
    "brand_ascii": "iphone"
}   
