### 
GET http://localhost:8080/api/categories

### 
GET http://localhost:8080/api/products/search?q=iphone 


### 
POST http://localhost:8080/api/products/search?page=0&size=2&sort=price,desc
Content-Type: application/json

{
    "category_id": "3"
}


###
POST http://localhost:8080/api/brands
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MTA0MzM1MzAsImlhdCI6MTcxMDQzMzUxNSwiYXV0aG9yaXRpZXMiOiJST0xFX0FETUlOIFJPTEVfVVNFUiJ9.BCMLEVtD9n-QXpMGmQwrkZo_fcNlpp-iiuHyg7dXdKsu8EiU-_SvtkdyZSqOpehYE4pGQwBBDKVc8__jQSqY7vB_k2hCgWmAE5IEXE-VMjMbo2DzjzPWtAqu5J4piw84KkU0lHHkVufVCdNB1WNqB-Z3cfekCnh_rKC20cpcsIpI9p2c3RM0G97D7o9rsbDTwbievioYXE3jMjPcimq4bgXMYxIR9SI-62tQiSbC8XpnrGLofmrgtMzxkrgW4HkAG-ZtBFGQebzY6SruL7BUbJYkLXGXbRWF74Ld9L_qQ4_epJ3naYpRXQiwWnvSXbEweo_E-732g6S8Gd1ZTc8HLg
content-Type: application/json

{
    "brand_name":"iPhone",
    "brand_ascii":"iphone",
    "category_id":"1"
}

###
PUT http://localhost:8080/api/products/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZGF0bmgiLCJleHAiOjE3MTA0NjU3NjEsImlhdCI6MTcxMDQ2NTc0NiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIifQ.EW7CwJZ9MGd7Jo2LPY7B3LO8_z1igehrBUhma1cqindWluznK42S-wJ6fDfHUg8a_TdxL7IrHYgXmb9VMkwhI-XiLpCdnHt0qySuaXA55bn2RyiL_YuuehA6Q_XHozivMHi-gPpyESRUz_479By6-4SzMFb3soU54r1P59bFpvTxpHaEKQst0zVKVSBpV8GOEqnI2GjQWhG_mt4E3kLQX6YLTKZh7kDK5CVhLAiBgPvAKdpVqZZIUgUAn6S5K17zF66d7VmfZrM2BGCOgzalll8vKVNnOfNB7j9nbM5uCQVBASlCyE1mRpnJvFVm9uBvGnqSkOPNV88YBvF_7PVoug

content-Type: application/json

{

    "product_name": "iPhone 14 Pro",
    "product_ascii": "iphone-14-pro",
    "category_id": 1,
    "brand_id": 2,
    "image_url": "http://res.cloudinary.com/dalg3ayqh/image/upload/v1709779286/hd-mobile/v7qwibrsujgj82xwkdfv.jpg",
    "price": 23890000,
    "installment": false
}


###
DELETE http://localhost:8080/api/products/1
# Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MTAzNTQ0NDAsImlhdCI6MTcxMDM0NzI0MCwiYXV0aG9yaXRpZXMiOiJST0xFX0FETUlOUk9MRV9VU0VSIn0.jeeg38EFo-Fm1QZwgmS8IbALZQwIB4hA0MUkTj7mZA78qFhDBTGanpjxSPFu0NtwPIBVmiSpOV5cnIfb55qlGzJ57o0TUsvxinUjSt6ARkJ4iwlK9biij3Fzyh0BSx1X89Uo9SxHzVFvOdbYjPwTXfWEwOrzq0kM0RSuPqOrjo8VqzqLKMI1ybS4q-7VceX7WYKN7NeXzwokJ8k82Nb6a60f39r7IWPmCb-yD8l3HF63gHxH42N3-0sGKd2Wz8a5p4pp1sig02kTjdI3DUKZADXFlivpA0XDW4cJti5VCECZdHKwOqwUICzO3_EHa2cj4gmfFmKjeeGJU0b2qKI4zw


###
POST http://localhost:8080/api/products
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZGF0bmgiLCJleHAiOjE3MTEwOTk5NTAsImlhdCI6MTcxMDM3OTk1MCwiYXV0aG9yaXRpZXMiOiJST0xFX0FETUlOIn0.ZfHn_Hz8T18QSvK3QvVT91fy9lzWZGZJSBZDj3QILSrVV6DaAQjM01GerSLmytIvDRit_RWWpzpRLwxTu6WSj48jbengJHk9zPra9W8UqWLi2TLjF6l480M7wxQhz1zQUosbyBwJu3jSiRXG-gfcYtaCIQ5S_y408ojcPgylkjvQ-jtZN9SDvegTF4mBhV-ObKDTkZZD5vFCpt48gNt3tVePBaZbW2kYwn8P0MWwUKZfI-uuoI2EIgVFkp2M5ezIi3Q0dTfFH2aj04MszSSnlD_Kj_1iPn2SgdwFb4x3nXXGNYjDEzJvyxCqxiLbfZWRlfClSPZ7B2OxdlOHsNU81Q
content-Type: application/json

{
    "product_name":"iPhone 15 Pro",
    "product_ascii":"iphone-15-pro",
    "category_id": "1",
    "brand_id":"1",
    "price": "23890000"
}   

###
GET http://localhost:8080/api/auth/refresh

###
POST http://localhost:8080/api/sliders
content-Type: application/json

{
    "product_name":"iPhone 15 Pro",
    "product_ascii":"iphone-15-pro",
    "category_id": "1",
    "brand_id":"1",
    "price": "23890000"
}   

###
POST http://localhost:8080/api/sliders
content-Type: application/json

{
"name": "home slider"
}   

###
POST http://localhost:8080/api/sliders/images
content-Type: application/json

{
"name": "home slider"
}   


